services:
  - name: agro-node
    type: web
    env: node
    rootDir: NODE
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false

  - name: agro-spring
    type: web
    env: docker
    rootDir: SPRING
    dockerfilePath: SPRING/Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: jdbc:mysql://localhost:3306/cadastro
        sync: false
      - key: root
        sync: false
      - key: senai508
        sync: false
